apiVersion: cluster.ray.io/v1
kind: RayCluster
metadata:
  annotations:
    kopf.zalando.org/last-handled-configuration: |
      {"spec":{"headPodType":"rayHeadType","headStartRayCommands":["ray stop","ulimit -n 65536; ray start --head --no-monitor --dashboard-host 0.0.0.0"],"idleTimeoutMinutes":5,"maxWorkers":2,"podTypes":[{"maxWorkers":0,"minWorkers":0,"name":"rayHeadType","podConfig":{"apiVersion":"v1","kind":"Pod","metadata":{"generateName":"ray-head-type-"},"spec":{"containers":[{"args":["trap : TERM INT; sleep infinity & wait;"],"command":["/bin/bash","-c","--"],"env":[{"name":"RAY_gcs_server_rpc_server_thread_num","value":"1"}],"image":"rayproject/ray:1.10.0-py38","imagePullPolicy":"Always","name":"ray-node","ports":[{"containerPort":6379,"protocol":"TCP"},{"containerPort":10001,"protocol":"TCP"},{"containerPort":8265,"protocol":"TCP"},{"containerPort":8000,"protocol":"TCP"}],"resources":{"limits":{"cpu":1,"memory":"1024Mi"},"requests":{"cpu":1,"memory":"1024Mi"}},"volumeMounts":[{"mountPath":"/dev/shm","name":"dshm"}]}],"restartPolicy":"Never","volumes":[{"emptyDir":{"medium":"Memory"},"name":"dshm"}]}},"rayResources":{"CPU":0}},{"maxWorkers":2,"minWorkers":2,"name":"rayWorkerType","podConfig":{"apiVersion":"v1","kind":"Pod","metadata":{"generateName":"ray-worker-type-"},"spec":{"containers":[{"args":["trap : TERM INT; sleep infinity & wait;"],"command":["/bin/bash","-c","--"],"env":[{"name":"RAY_gcs_server_rpc_server_thread_num","value":"1"}],"image":"rayproject/ray:1.10.0-py38","imagePullPolicy":"Always","name":"ray-node","ports":[{"containerPort":6379,"protocol":"TCP"},{"containerPort":10001,"protocol":"TCP"},{"containerPort":8265,"protocol":"TCP"},{"containerPort":8000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"2","memory":"1Gi"}},"volumeMounts":[{"mountPath":"/dev/shm","name":"dshm"}]}],"restartPolicy":"Never","volumes":[{"emptyDir":{"medium":"Memory"},"name":"dshm"}]}}}],"upscalingSpeed":1,"workerStartRayCommands":["ray stop","ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379"]},"metadata":{"labels":{"app.kubernetes.io/managed-by":"Helm"},"annotations":{"meta.helm.sh/release-name":"example-cluster","meta.helm.sh/release-namespace":"ray"}},"status":{"autoscalerRetries":0}}
    meta.helm.sh/release-name: example-cluster
    meta.helm.sh/release-namespace: ray
  creationTimestamp: "2022-05-13T20:04:15Z"
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: example-cluster
  namespace: ray
  resourceVersion: "679"
  uid: 49b93ea5-e01b-40fd-824c-35b24cb8a296
spec:
  headPodType: rayHeadType
  headStartRayCommands:
  - ray stop
  - ulimit -n 65536; ray start --head --no-monitor --dashboard-host 0.0.0.0
  idleTimeoutMinutes: 5
  maxWorkers: 2
  podTypes:
  - maxWorkers: 0
    minWorkers: 0
    name: rayHeadType
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        generateName: ray-head-type-
      spec:
        containers:
        - args:
          - 'trap : TERM INT; sleep infinity & wait;'
          command:
          - /bin/bash
          - -c
          - --
          env:
          - name: RAY_gcs_server_rpc_server_thread_num
            value: "1"
          image: rayproject/ray:1.10.0-py38
          imagePullPolicy: Always
          name: ray-node
          ports:
          - containerPort: 6379
            protocol: TCP
          - containerPort: 10001
            protocol: TCP
          - containerPort: 8265
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 1
              memory: 1024Mi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        restartPolicy: Never
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
    rayResources:
      CPU: 0
  - maxWorkers: 2
    minWorkers: 2
    name: rayWorkerType
    podConfig:
      apiVersion: v1
      kind: Pod
      metadata:
        generateName: ray-worker-type-
      spec:
        containers:
        - args:
          - 'trap : TERM INT; sleep infinity & wait;'
          command:
          - /bin/bash
          - -c
          - --
          env:
          - name: RAY_gcs_server_rpc_server_thread_num
            value: "1"
          image: rayproject/ray:1.10.0-py38
          imagePullPolicy: Always
          name: ray-node
          ports:
          - containerPort: 6379
            protocol: TCP
          - containerPort: 10001
            protocol: TCP
          - containerPort: 8265
            protocol: TCP
          - containerPort: 8000
            protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: "2"
              memory: 1Gi
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
        restartPolicy: Never
        volumes:
        - emptyDir:
            medium: Memory
          name: dshm
  upscalingSpeed: 1
  workerStartRayCommands:
  - ray stop
  - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379
status:
  autoscalerRetries: 0
  kopf:
    progress: {}
  phase: Running
