apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-server-deployment
  labels:
    app: contentServer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contentServer
  template:
    metadata:
      name: content-server-pod
      labels:
        app: contentServer
    spec:
      containers:
      - name: content-server
        image: resourceless/content-server
        ports:
        - containerPort: 80
        imagePullPolicy: Never